
# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 18:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0006_require_contenttypes_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faqlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('group', models.CharField(blank=True, default='', max_length=250)),
                ('title', models.CharField(blank=True, default='', max_length=250)),
                ('text', models.TextField())
            ],
            options={
                'ordering': ('created',),
            },
        ),
]
